# PVC for storing the test-output artifacts created during a test run
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ods-ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    deployment: ods-ci
  name: ods-ci
spec:
  securityContext:
    # This is required to make the test-output volume Writable
    fsGroup: 0
  containers:
    - image: quay.io/spryor/ods-ci:latest
      imagePullPolicy: Always
      name: ods-ci
      command: ["/bin/sh"]
      args: ["-c", "./run.sh; touch /tmp/completed; sleep 100"]
      env:
        # Use this environment variable to pass args to the ods-ci run script in the container
        - name: RUN_SCRIPT_ARGS
          value: "--test-variables-file /tmp/ods-ci-test-variables/test-variables.yml --include sanity"
      volumeMounts:
          # Mount the test-variables to prevent leaking secure info for the cluster you test against
        - name: ods-ci-test-variables
          mountPath: /tmp/ods-ci-test-variables

        - mountPath: /tmp/ods-ci/test-output
          name: ods-ci-test-output
  restartPolicy: Never
  volumes:
    - name: ods-ci-test-variables
      secret:
        # Specify Secret that has the necessary test-variables.yml
        secretName: ods-ci-test-variables
    # Persistent Volume where we will store the test-output for this pod
    - name: ods-ci-test-output
      persistentVolumeClaim:
        claimName: ods-ci
